### ISSUE TITLE
Does this template support monitoring rabbitmq clusters? 

### ISSUE THREAD

**Issue by JenkinLee** [jasonmcintosh/rabbitmq-zabbix#101]
Hi!
Does the template support monitoring rabbitmq clusters? Or is there a similar solution?
thanks!

**Comment by jasonmcintosh** [comment]
Clusters are always a challenge due to the data.  What you can do is setup the template, then create a duplicate of the template WITHOUT the queue monitoring.  The server calls should be specific to the server being monitored.  

SO yes, it can monitor a rabbitmq cluster... just have to watch the queues being duplicated across nodes, leading to duplicate alerts & such.
