### ISSUE TITLE
urlopen error [Errno 111] Connection refused

### ISSUE THREAD

**Issue by itJunky** [jasonmcintosh/rabbitmq-zabbix#35]
What i'm doing wrong?

After update scripts i'm get an error:
root@zabbix:~# zabbix_get -s 136.x.x.135 -k rabbitmq.discovery_queue
or with manually run at client
w2:/etc/zabbix# sudo -u zabbix /etc/zabbix/scripts/rabbitmq/list_rabbit_queues.sh
```
Traceback (most recent call last):
  File "./api.py", line 209, in <module>
    main()
  File "./api.py", line 192, in main
    print json.dumps({'data': api.list_queues(filters)})
  File "./api.py", line 46, in list_queues
    for queue in self.call_api('queues'):
  File "./api.py", line 36, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

```

**Comment by itJunky** [comment]
I found port is not listening by set "print url" to line 36 of api.py and see what port used by apy.py (15672) but it wrong port =(
`# /etc/init.d/rabbitmq-server status | grep pid
[{pid,6329},
# netstat -nlpt | grep 6329
tcp        0      0 0.0.0.0:45000           0.0.0.0:*               LISTEN      6329/beam.smp   
tcp6       0      0 :::5672                 :::*                    LISTEN      6329/beam.smp  `

**Comment by jasonmcintosh** [comment]
RabbitMQ runs with the AMQP protocol on port 5672.  This is NOT a monitoring port, but just for communications over that protocol - see https://www.amqp.org/ for info.

You need to enable the management plugins.  These plugins provide the web interface for administration purposes.

**Comment by itJunky** [comment]
Thanks for your help. But monitoring start to work after reboot RMQ daemon. It's bug of RMQ.

**Comment by hamiltonfvi** [comment]
Hey itJunky, what did you do to solve the problem? Im having the same issue.

**Comment by jasonmcintosh** [comment]
You MUST have the web interface enabled as a plugin.  The web admin interface listens on port 15672.  Port 5672 is JUST the AMQP protocol interface.  

IF you have the web interface enabled, netstat shows 15672 open, then next guess is a firewall issue.  You should be able to from a browser go to your server http://server:15672/ and see the admin interface.

**Comment by hamiltonfvi** [comment]
thanks a lot for replay, my web interface wasnt working before, but it started working as soon as I restarted the rabbitmq-server. Now Im able to go to the web GUI Interface, login and work with everything, except that zabbix isnt capturing nothing. Do you think this behavior is maybe because this is just a recent installation and still doesnt have anything added? I mean, channels, queues, hosts, etc?

if run the scripts manually, I got: 

 ./list_rabbit_nodes.sh
Traceback (most recent call last):
  File "./api.py", line 212, in <module>
    main()
  File "./api.py", line 197, in main
    print json.dumps({'data': api.list_nodes()})
  File "./api.py", line 63, in list_nodes
    for node in self.call_api('nodes'):
  File "./api.py", line 37, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: **<urlopen error [Errno 111] Connection refused>**

the .rab.auth file is correct, it is according to the configuration you posted. 
I gave full permissions to everyone in the whole directory **python2.7** (just to see if this is the issue) but Im still having the same problem. 

Thanks in advance for the great contribution anyway
